name: MobStacker
main: com.kiwifisher.mobstacker.MobStacker
author: KiwiFisher
version: 1.9
softdepend: [WorldGuard]
commands:
  mobstacker:
    permission-message: You don't have access to that command!
